version: '3.0'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - docker-node
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mysql
    networks:
      - docker-node

networks: #定义服务的桥 用来服务连接
  docker-node: